export const metadata = {
  title: 'Sydar Links',
  description: 'Generated by Create Next App',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body>{children}</body>
    </html>
  )
}
